application: sicktako
version: 1
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- remote_api: on

inbound_services:
- warmup

handlers:
- url: /_ah/queue/deferred
  script: djangoappengine.deferred.handler.application
  login: admin

- url: /_ah/stats/.*
  script: djangoappengine.appstats.application

- url: /media/admin
  static_dir: django/contrib/admin/media
  expiration: '0'

- url: /
  static_files: static/s/index.html
  upload: static/s/index.html
- url: /sss
  static_dir: static/sss


- url: /.*
  script: djangoappengine.main.application

- url: /.*
  static_files: static/s/404.html
  upload: static/s/404.html
